name: Validate vomses

on:
  pull_request:
  push:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: validate Travis
      run: bin/vomses-crosscheck vomses vomsdir
