name: Validate DN Format

on:
  pull_request:
  push:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: validate dn format
      run: bin/validate_dn_format.py